<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <YMM4DirPath Condition="'$(YMM4DirPath)' == ''">C:\Program Files\YukkuriMovieMaker4\</YMM4DirPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="YukkuriMovieMaker.Controls">
      <HintPath>$(YMM4DirPath)YukkuriMovieMaker.Controls.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="YukkuriMovieMaker.Plugin">
      <HintPath>$(YMM4DirPath)YukkuriMovieMaker.Plugin.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
